### ISSUE TITLE
Exception on oai import -c

### ISSUE THREAD

**Issue by kosarko** [vidiecan/DSpace#38]
```
$ sudo -u tomcat7 /installations/dspace/dspace-1.8.2/bin/dspace oai import -c
OAI 2.0 manager action started
Clearing index
Index cleared
Using full import.
Full import
java.lang.NullPointerException
    at cz.cuni.mff.ufal.lindat.utilities.hibernate.HibernateUtil.closeSession(HibernateUtil.java:83)
    at cz.cuni.mff.ufal.lindat.utilities.HibernateFunctionalityManager.closeSession(HibernateFunctionalityManager.java:637)
    at cz.cuni.mff.ufal.lindat.utilities.HibernateFunctionalityManager.close(HibernateFunctionalityManager.java:731)
    at org.dspace.xoai.util.ItemUtils.retrieveMetadata(ItemUtils.java:261)
    at org.dspace.xoai.app.XOAI.index(XOAI.java:277)
    at org.dspace.xoai.app.XOAI.index(XOAI.java:212)
    at org.dspace.xoai.app.XOAI.indexAll(XOAI.java:199)
    at org.dspace.xoai.app.XOAI.index(XOAI.java:132)
    at org.dspace.xoai.app.XOAI.main(XOAI.java:406)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
    at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:77)
```

**Comment by kosarko** [comment]
java.lang.NullPointerException
        at cz.cuni.mff.ufal.lindat.utilities.hibernate.HibernateUtil.findByCriterie(HibernateUtil.java:329)
        at cz.cuni.mff.ufal.lindat.utilities.HibernateFunctionalityManager.getLicenses(HibernateFunctionalityManager.java:185)
        at org.dspace.xoai.util.ItemUtils.retrieveMetadata(ItemUtils.java:242)
        at org.dspace.xoai.app.XOAI.index(XOAI.java:277)
        at org.dspace.xoai.app.XOAI.index(XOAI.java:212)
        at org.dspace.xoai.app.XOAI.indexAll(XOAI.java:199)
        at org.dspace.xoai.app.XOAI.index(XOAI.java:132)
        at org.dspace.xoai.app.XOAI.main(XOAI.java:406)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:77)

**Comment by kosarko** [comment]
caused by org.hibernate.exception.GenericJDBCException: Could not open connection

the test env has very limited resources and the hibernate/dspace config is not in sync with postgres setting...
